#!/usr/bin/env python

import os
import sys
import torch
from diffusers import StableDiffusionXLPipeline

# append project directory to path so predict.py can be imported
sys.path.append('.')

from predict import MODEL_CACHE

# Make cache folder
if not os.path.exists(MODEL_CACHE):
    os.makedirs(MODEL_CACHE)

# Stable Diffusion XL
pipe = StableDiffusionXLPipeline.from_single_file(
    "https://huggingface.co/asiryan/juggernautXL/blob/main/juggernautXL_v7Rundiffusion.safetensors",
    torch_dtype=torch.float16,
)
pipe.save_pretrained(MODEL_CACHE)
